//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""CamMovement"",
            ""id"": ""2624ff4b-5ea7-4c3d-a734-4ad0a4251c62"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3663715b-8cc1-45b5-a656-90f3f6c3c274"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d4506616-18d6-4237-a86b-37d1c53b07bb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""9e20beaa-40da-4536-8d75-6301e5ff8011"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""7f60e232-b92e-4c9d-b3a0-893f3b29c44c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""wasd"",
                    ""id"": ""c2b78e1d-a330-472e-9ff2-96dba634be75"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""263f8c6e-ffff-4903-be12-a280828dad5c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c735df38-176c-40a0-8558-897e12081d77"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""53d48758-ff37-4c2e-b368-e9c509696080"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""49e35772-e62b-4bd9-8d80-6f6463444637"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c4ff2286-6310-42e8-95bb-42276c3568c8"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46eec119-cd18-442c-a85a-baf2ef31d990"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2dc0dbf-6c44-41b8-8f6e-17ae4b1b3113"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CamMovement
        m_CamMovement = asset.FindActionMap("CamMovement", throwIfNotFound: true);
        m_CamMovement_Move = m_CamMovement.FindAction("Move", throwIfNotFound: true);
        m_CamMovement_Zoom = m_CamMovement.FindAction("Zoom", throwIfNotFound: true);
        m_CamMovement_Click = m_CamMovement.FindAction("Click", throwIfNotFound: true);
        m_CamMovement_MousePos = m_CamMovement.FindAction("MousePos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CamMovement
    private readonly InputActionMap m_CamMovement;
    private ICamMovementActions m_CamMovementActionsCallbackInterface;
    private readonly InputAction m_CamMovement_Move;
    private readonly InputAction m_CamMovement_Zoom;
    private readonly InputAction m_CamMovement_Click;
    private readonly InputAction m_CamMovement_MousePos;
    public struct CamMovementActions
    {
        private @PlayerControls m_Wrapper;
        public CamMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CamMovement_Move;
        public InputAction @Zoom => m_Wrapper.m_CamMovement_Zoom;
        public InputAction @Click => m_Wrapper.m_CamMovement_Click;
        public InputAction @MousePos => m_Wrapper.m_CamMovement_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_CamMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CamMovementActions set) { return set.Get(); }
        public void SetCallbacks(ICamMovementActions instance)
        {
            if (m_Wrapper.m_CamMovementActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMove;
                @Zoom.started -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnZoom;
                @Click.started -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnClick;
                @MousePos.started -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_CamMovementActionsCallbackInterface.OnMousePos;
            }
            m_Wrapper.m_CamMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
            }
        }
    }
    public CamMovementActions @CamMovement => new CamMovementActions(this);
    public interface ICamMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
}
